name: Publish Docker image

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - renovate/**
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}  # <organization>/<repository>
  BUILD_ARCHITECTURES: linux/amd64,linux/arm64

jobs:
  build-image:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          push: false
          platforms: ${{ env.BUILD_ARCHITECTURES }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  push-to-edge:
    name: Push images (edge tag)
    runs-on: ubuntu-latest
    needs: [ build-image ]
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.token }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          context: git
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=edge,branch=${{ github.ref_name }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          platforms: ${{ env.BUILD_ARCHITECTURES }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
      - run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:edge

  push-to-version:
    name: Push images (versioned tags)
    runs-on: ubuntu-latest
    needs: [ build-image ]
    if: ${{ github.event_name == 'release' }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.token }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          context: git
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          platforms: ${{ env.BUILD_ARCHITECTURES }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
      - run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.GITHUB_REF_NAME }}:
